// import '../services/whatsapp_service.dart';

// /// Utility class for common WhatsApp sharing operations in the accounting app
// class WhatsAppAccountingUtils {
//   static final WhatsAppService _whatsappService = WhatsAppService();

//   /// Share expense details
//   static Future<bool> shareExpense({
//     required String expenseId,
//     required double amount,
//     required String currency,
//     required String category,
//     required String description,
//     required DateTime date,
//     String? phoneNumber,
//   }) async {
//     final buffer = StringBuffer();
//     buffer.writeln('💰 Expense Details');
//     buffer.writeln('ID: $expenseId');
//     buffer.writeln('Amount: $currency ${amount.toStringAsFixed(2)}');
//     buffer.writeln('Category: $category');
//     buffer.writeln('Date: ${date.toString().split(' ')[0]}');

//     if (description.isNotEmpty) {
//       buffer.writeln('Description: $description');
//     }

//     buffer.writeln('\n📊 Shared from Matrix Accounts');

//     return await _whatsappService.shareText(
//       buffer.toString(),
//       phoneNumber: phoneNumber,
//     );
//   }

//   /// Share income details
//   static Future<bool> shareIncome({
//     required String incomeId,
//     required double amount,
//     required String currency,
//     required String source,
//     required String description,
//     required DateTime date,
//     String? phoneNumber,
//   }) async {
//     final buffer = StringBuffer();
//     buffer.writeln('💵 Income Details');
//     buffer.writeln('ID: $incomeId');
//     buffer.writeln('Amount: $currency ${amount.toStringAsFixed(2)}');
//     buffer.writeln('Source: $source');
//     buffer.writeln('Date: ${date.toString().split(' ')[0]}');

//     if (description.isNotEmpty) {
//       buffer.writeln('Description: $description');
//     }

//     buffer.writeln('\n📊 Shared from Matrix Accounts');

//     return await _whatsappService.shareText(
//       buffer.toString(),
//       phoneNumber: phoneNumber,
//     );
//   }

//   /// Share invoice with detailed information
//   static Future<bool> shareDetailedInvoice({
//     required String invoiceNumber,
//     required String customerName,
//     required double subtotal,
//     required double tax,
//     required double total,
//     required String currency,
//     required DateTime dueDate,
//     required List<Map<String, dynamic>> items,
//     String? notes,
//     String? phoneNumber,
//   }) async {
//     final buffer = StringBuffer();
//     buffer.writeln('🧾 INVOICE');
//     buffer.writeln('Invoice #: $invoiceNumber');
//     buffer.writeln('Customer: $customerName');
//     buffer.writeln('Due Date: ${dueDate.toString().split(' ')[0]}');
//     buffer.writeln('');

//     // Add line items
//     buffer.writeln('📋 Items:');
//     for (var item in items) {
//       buffer.writeln(
//           '• ${item['description']} - ${item['quantity']} × $currency${item['unitPrice']} = $currency${item['total']}');
//     }

//     buffer.writeln('');
//     buffer.writeln('💰 Summary:');
//     buffer.writeln('Subtotal: $currency ${subtotal.toStringAsFixed(2)}');
//     buffer.writeln('Tax: $currency ${tax.toStringAsFixed(2)}');
//     buffer.writeln('Total: $currency ${total.toStringAsFixed(2)}');

//     if (notes != null && notes.isNotEmpty) {
//       buffer.writeln('\n📝 Notes: $notes');
//     }

//     buffer.writeln('\n📊 Generated by Matrix Accounts');

//     return await _whatsappService.shareText(
//       buffer.toString(),
//       phoneNumber: phoneNumber,
//     );
//   }

//   /// Share monthly financial summary
//   static Future<bool> shareFinancialSummary({
//     required String companyName,
//     required DateTime month,
//     required double totalIncome,
//     required double totalExpenses,
//     required double netProfit,
//     required String currency,
//     required Map<String, double> expensesByCategory,
//     String? phoneNumber,
//   }) async {
//     final monthName = _getMonthName(month.month);
//     final year = month.year;

//     final buffer = StringBuffer();
//     buffer.writeln('📈 FINANCIAL SUMMARY');
//     buffer.writeln('Company: $companyName');
//     buffer.writeln('Period: $monthName $year');
//     buffer.writeln('');

//     buffer.writeln('💰 Overview:');
//     buffer.writeln('Total Income: $currency ${totalIncome.toStringAsFixed(2)}');
//     buffer.writeln(
//         'Total Expenses: $currency ${totalExpenses.toStringAsFixed(2)}');
//     buffer.writeln('Net Profit: $currency ${netProfit.toStringAsFixed(2)}');

//     if (expensesByCategory.isNotEmpty) {
//       buffer.writeln('\n📊 Expenses by Category:');
//       expensesByCategory.forEach((category, amount) {
//         buffer.writeln('• $category: $currency ${amount.toStringAsFixed(2)}');
//       });
//     }

//     buffer.writeln('\n📊 Generated by Matrix Accounts');

//     return await _whatsappService.shareText(
//       buffer.toString(),
//       phoneNumber: phoneNumber,
//     );
//   }

//   /// Share party/contact information
//   static Future<bool> sharePartyInfo({
//     required String partyName,
//     required String partyType,
//     String? phone,
//     String? email,
//     String? address,
//     double? balance,
//     String? currency,
//     String? phoneNumber,
//   }) async {
//     final buffer = StringBuffer();
//     buffer.writeln('👥 CONTACT INFORMATION');
//     buffer.writeln('Name: $partyName');
//     buffer.writeln('Type: $partyType');

//     if (phone != null && phone.isNotEmpty) {
//       buffer.writeln('Phone: $phone');
//     }

//     if (email != null && email.isNotEmpty) {
//       buffer.writeln('Email: $email');
//     }

//     if (address != null && address.isNotEmpty) {
//       buffer.writeln('Address: $address');
//     }

//     if (balance != null && currency != null) {
//       buffer.writeln('Balance: $currency ${balance.toStringAsFixed(2)}');
//     }

//     buffer.writeln('\n📊 Shared from Matrix Accounts');

//     return await _whatsappService.shareText(
//       buffer.toString(),
//       phoneNumber: phoneNumber,
//     );
//   }

//   /// Share account balance information
//   static Future<bool> shareAccountBalance({
//     required String accountName,
//     required double balance,
//     required String currency,
//     required DateTime asOfDate,
//     String? notes,
//     String? phoneNumber,
//   }) async {
//     final buffer = StringBuffer();
//     buffer.writeln('🏦 ACCOUNT BALANCE');
//     buffer.writeln('Account: $accountName');
//     buffer.writeln('Balance: $currency ${balance.toStringAsFixed(2)}');
//     buffer.writeln('As of: ${asOfDate.toString().split(' ')[0]}');

//     if (notes != null && notes.isNotEmpty) {
//       buffer.writeln('Notes: $notes');
//     }

//     buffer.writeln('\n📊 From Matrix Accounts');

//     return await _whatsappService.shareText(
//       buffer.toString(),
//       phoneNumber: phoneNumber,
//     );
//   }

//   /// Share backup notification
//   static Future<bool> shareBackupNotification({
//     required String companyName,
//     required DateTime backupDate,
//     required String backupSize,
//     required bool isSuccessful,
//     String? phoneNumber,
//   }) async {
//     final buffer = StringBuffer();
//     buffer.writeln(isSuccessful ? '✅ BACKUP SUCCESSFUL' : '❌ BACKUP FAILED');
//     buffer.writeln('Company: $companyName');
//     buffer.writeln('Date: ${backupDate.toString().split(' ')[0]}');

//     if (isSuccessful) {
//       buffer.writeln('Size: $backupSize');
//       buffer.writeln('Status: Backup completed successfully');
//     } else {
//       buffer.writeln('Status: Backup failed - please check the system');
//     }

//     buffer.writeln('\n📊 Matrix Accounts Backup System');

//     return await _whatsappService.shareText(
//       buffer.toString(),
//       phoneNumber: phoneNumber,
//     );
//   }

//   /// Share report file with description
//   static Future<bool> shareReportFile({
//     required String filePath,
//     required String reportName,
//     required String reportType,
//     required DateTime generatedDate,
//     String? description,
//     String? phoneNumber,
//   }) async {
//     final buffer = StringBuffer();
//     buffer.writeln('📄 $reportType Report');
//     buffer.writeln('Name: $reportName');
//     buffer.writeln('Generated: ${generatedDate.toString().split(' ')[0]}');

//     if (description != null && description.isNotEmpty) {
//       buffer.writeln('Description: $description');
//     }

//     buffer.writeln('\n📊 Generated by Matrix Accounts');

//     return await _whatsappService.shareFile(filePath, text: buffer.toString());
//   }

//   /// Get month name from month number
//   static String _getMonthName(int month) {
//     const months = [
//       'January',
//       'February',
//       'March',
//       'April',
//       'May',
//       'June',
//       'July',
//       'August',
//       'September',
//       'October',
//       'November',
//       'December'
//     ];
//     return months[month - 1];
//   }
// }
